name: Build and Package VS Code Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - run: npm install
      - run: npm run prebuild
      - run: npm run build
      - run: npm run package

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: "*.vsix"
