on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: "20"

  - name: Install dependencies
    run: npm install --no-save @vscode/vsce

  - name: Build extension
    run: npx vsce package

  - name: Archive artifact
    uses: actions/upload-artifact@v2
    with:
      name: *.vsix
      path: path/to/your/artifact
