name: Package VSCode Extension
on:
  push:
    branches:
      - main
jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install VSCE
        run: npm install --no-save @vscode/vsce

      - name: Package extension
        run: npx @vscode/vsce package

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: "*.vsix"
